config/routes.rb
Rails.application.routes.draw do

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  	get 'pages/home'
	
	# get 'pages/home', to: 'pages#home'
	root 'pages#home'
	get 'about', to: 'pages#about'
  	

  	# This will give new, edit , patch and get article path. To check, rails routes is the command
  	resources :articles





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# Article Model
class Article < ApplicationRecord
	# validates the title and description fields in the Articles tables.
	validates :title, presence: true, length: { minimum:3, maximum: 50 }
	validates :description, presence: true, length: { minimum:3, maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
# Articles Controller
class ArticlesController < ApplicationController
	# Call set article before edit, update, show and destroy !
	before_action :set_article, only: [:edit, :update, :show, :destroy]

	# New Article
	def new 
		@article = Article.new
	end

	# Save an article and show the article to the user.	
	def create
		# Able to see whats being displayed in the browser
		# render plain: params[:article].inspect

		# Created a new article instance variable passing the another method
		@article = Article.new(article_params)

		# save the article
		# @article.save

		# putting in some validations
		if @article.save
			flash[:notice] = "Article was successfully created!"
			redirect_to article_path(@article)
		else
			render 'new'
		end
		# redirect to show method in the article
		# redirect_to article_path(@article)
	end

	def show
			set_article
	end

	# Edit an article and update action
	def edit
		set_article
	end

	def update
		set_article
		if @article.update(article_params)
			flash[:notice] = "Article was successfully updated!"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	# Displays the articles to the user	
	def index
		@articles = Article.all
	end

	def destroy
		set_article
		@article.destroy
		flash[:notice] = "Article was successfully deleted!"
		redirect_to articles_path
	end


	private
	def article_params
		# It will take the fields from the render part above and fetch title and description values
		params.require(:article).permit(:title, :description)
	end

	def set_article
		@article = Article.find(params[:id])
	end
end
 

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<!-- Partials - Use of DRY Code as we had this same form in new and edit html erb forms -->
<% if @article.errors.any? %>
<h2>The following errors prevented the article from getting created</h2>
<ul>
		<% @article.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end  %>
</ul>
<% end %>


<%= form_for @article do |f| %>
	<p>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :description %>
		<%= f.text_area :description %>
	</p>
	<p><%= f.submit %></p>
<% end %>

<%=link_to 'Back to articles listing', articles_path%>

app/views/articles/create.html.erb
<!-- <h1>Article saved successfully!</h1> -->

app/views/articles/edit.html.erb
<h1>Edit an existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing all articles</h1>
<p>
<%=link_to 'Create a New Article', new_article_path%>
</p>

<table>
	<tr>
		<th>Title</th>
		<th> Description</th>
	</tr>

	<% @articles.each do |article| %>
		<tr>
			<td><%= article.title %></td>
			<td><%= article.description %></td>
			<td><%=link_to 'Edit', edit_article_path(article)%></td>
			<td><%=link_to 'Show', article_path(article)%></td>
			<td><%=link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
		</tr>
	<% end %>
</table>

app/views/articles/new.html.erb
<h1>Create an Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<p> Title: <%= @article.title %> </p>
<p> Description: <%= @article.description %></p>

<%=link_to 'Edit this article', edit_article_path(@article)%> |

<%=link_to 'Back to articles listing', articles_path%>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg | %>
	<ul>
		<li><%= msg %></li>
	</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SushantBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
	<body>
	<%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>

<%=link_to 'Home', root_path%>

app/views/pages/home.html.erb
<h1>HomePage</h1>
<!-- <p>Find me in app/views/pages/home.html.erb</p> -->

<!-- check the rails routes in order to check the path in the link and pages. -->
<%=link_to 'About', about_path%>

<!-- Takes you to a new article page -->
<%=link_to 'Create a New Article', new_article_path%>
<%=link_to 'My Blog', articles_path%>